### ISSUE TITLE
Website not working 

### ISSUE THREAD

**Issue by mgr98** [ashleymaeconard/TIMEOR#15]
Hi, 

I've tried the website https://timeor.brown.edu/ since yesterday using different browsers and computers, but it is not working. Can someone please check if the website is working from them? 

Thank you!!!

**Comment by ashleymaeconard** [comment]
Thank you! Everything is up and running! We are also implementing automatic testing to ensure that we are pinged if this problem happens again. Please feel free to email ashley_conard@brown.edu if you have further questions about your specific study design and TIMEOR's supported study designs! I am happy to address other questions as well.
