### ISSUE TITLE
Disconnects from the server and forces a reload

### ISSUE THREAD

**Issue by mgr98** [ashleymaeconard/TIMEOR#16]
Hi, 

I have been able to complete the preprocess step with no issues using the metadata and counts as indicated in the tutorial. **_However, once I get to the primary analysis the app disconnects from the server right after I press RUN._** 

I have the same issue with both the app and running it locally with docker. What could this be? Any help is appreciated, thank you :) 

Here is the head of of my metadata and counts 

<img width="772" alt="Screen Shot 2021-06-29 at 4 54 39 PM" src="https://user-images.githubusercontent.com/62923042/123866261-d0b6da00-d8fa-11eb-96ef-7eae48b0c32c.png">
<img width="262" alt="Screen Shot 2021-06-29 at 4 55 05 PM" src="https://user-images.githubusercontent.com/62923042/123866317-e6c49a80-d8fa-11eb-88f9-ba890fc03069.png">

**Comment by ashleymaeconard** [comment]
One of the things that I see immediately is that the metadata and count matrices should have all the same ordered identifiers. Is that the case? This seems to be a user data specific issue. On the first page of TIMEOR I show several specifications for the input. As I mention there, feel free to email me (ashley_conard@brown.edu) for log file and your data questions. I can provide catered responses there!
