### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by BhardwajArch** [ashleymaeconard/TIMEOR#17]
Hello 
I am trying to run the TIMEOR webserver with raw count matrix data.  I prepared all the input files (metadata and count matrix) as recommended. Until pre-process tab, everything works fine. But in *Primary Analysis ** tab, I am getting following error: 
error is **"Disconnected from server", "Reload"**

Please help me to fix this issue.

**Comment by ashleymaeconard** [comment]
Hi @BhardwajArch, thank you for using TIMEOR. On the instruction page is says to please attach the log file so I can adequately diagnose the issue. Also, how long did you have the window open without doing anything? If you do not want to attach the log file to this chat you can email/message it to me.

**Comment by ashleymaeconard** [comment]
Also @BhardwajArch please always feel free to email or ping me again if I do not respond in the timeframe you need.

**Comment by helmutcarter** [comment]
Hello @ashleymaeconard I am having the same problem. As the log file is rather long, I've uploaded it on pastebin at https://pastebin.com/5W3VA29Z Thank you!

**Comment by ashleymaeconard** [comment]
Great @helmutcarter thank you. I will check in with my team and get back to you!

**Comment by ashleymaeconard** [comment]
I have 2 follow-up questions @helmutcarter. 1) do you have duplicated genes in your data? 2) did you allow for all 3 differentially expressed gene methods to run? I think I know the answers to these questions and want to confirm.
