### ISSUE TITLE
error during the installation "Error in tag"

### ISSUE THREAD

**Issue by archanabhardwaj** [ashleymaeconard/TIMEOR#5]
Hello 

I am having following issue during runtime of TIMEOR. 

Warning: package ‘shinycssloaders’ was built under R version 3.6.3
Warning: Error in tag: argument is missing, with no default
  75: tag
  74: tags$div
  73: div
  72: fluidRow

As a result , browser web link is displaying following error : 

ERROR: argument is missing, with no default

Could you help me to fix this issue ? 

Thanks in advance 
A

**Comment by ashleymaeconard** [comment]
Hello - yes certainly! Are you installing using Conda env or Docker? What type of machine are you using?

**Comment by ashleymaeconard** [comment]
Okay well I am going to close this for now as I haven't heard from you but please reach out if needed!
